### ISSUE TITLE
Bug no editor de ship.

### ISSUE THREAD

**Issue by NotIsJoa** [LorittaBot/DreamLand#248]
**Qual é o problema?**

Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

1. Eu fui mudar o valor do ship, mais aparecia um bug, e pedia para eu escrever o código do bug aqui, então aqui está

<html>
<head>
<title>Uh, oh! Something went wrong!</title>
</head>
<body>
<pre>net.dv8tion.jda.api.exceptions.ErrorResponseException: 10013: Unknown User
	at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
	at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
	at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:270)
	at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:237)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:141)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:124)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.&lt;init&gt;(Request.java:71)
	at net.dv8tion.jda.api.requests.RestFuture.&lt;init&gt;(RestFuture.java:36)
	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
	at net.dv8tion.jda.api.requests.RestAction.submit(RestAction.java:694)
	at com.mrpowergamerbr.loritta.utils.extensions.JDAExtensionsKt.await(JDAExtensions.kt:16)
	at com.mrpowergamerbr.loritta.utils.LorittaShards.retrieveUserById(LorittaShards.kt:195)
	at com.mrpowergamerbr.loritta.utils.LorittaShards.retrieveUserInfoById(LorittaShards.kt:132)
	at com.mrpowergamerbr.loritta.utils.LorittaShards$retrieveUserInfoById$1.invokeSuspend(LorittaShards.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion$create$factory$1$1.run(NettyApplicationEngine.kt:227)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
</pre>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"698749058c7a51ae","token":"ccc023e17afd401b8ee47740d83deee4","version":"2021.9.0","si":100}'></script>
</body>
</html>

**Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

**Comment by MrPowerGamerBR** [comment]
Isso é um bug conhecido quando o usuário não está no cache dela, a solução por enquanto é colocar o ID da pessoa
